/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.oopassignment3;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;


public class loginpagecashier extends javax.swing.JFrame {

  Connection c = null;
  PreparedStatement p = null;
  ResultSet r = null;
  
    public loginpagecashier() {
        initComponents();
                c = Oopassignment3.c();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        login = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        usernamef = new javax.swing.JTextField();
        passwordf = new javax.swing.JPasswordField();
        password = new javax.swing.JLabel();
        loginbtn = new javax.swing.JButton();
        cancelbtn = new javax.swing.JButton();
        username1 = new javax.swing.JLabel();
        loginbtn1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        login.setFont(new java.awt.Font("Nirmala UI", 1, 30)); // NOI18N
        login.setText("Cashier Sign in");
        getContentPane().add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, -1, -1));

        username.setBackground(new java.awt.Color(0, 0, 0));
        username.setFont(new java.awt.Font("Nirmala UI", 1, 15)); // NOI18N
        username.setText("If you are an admin, Please sign in Here...");
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, -1, -1));

        usernamef.setBackground(new java.awt.Color(255, 255, 51));
        usernamef.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        getContentPane().add(usernamef, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 160, -1));

        passwordf.setBackground(new java.awt.Color(255, 255, 51));
        passwordf.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        getContentPane().add(passwordf, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 160, -1));

        password.setBackground(new java.awt.Color(0, 0, 0));
        password.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        password.setText("Password");
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, -1, -1));

        loginbtn.setBackground(new java.awt.Color(255, 255, 0));
        loginbtn.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        loginbtn.setText("SIGN IN");
        loginbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbtnActionPerformed(evt);
            }
        });
        getContentPane().add(loginbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 450, -1, -1));

        cancelbtn.setBackground(new java.awt.Color(255, 255, 0));
        cancelbtn.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        cancelbtn.setText("CANCEL");
        cancelbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelbtnActionPerformed(evt);
            }
        });
        getContentPane().add(cancelbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, -1, -1));

        username1.setBackground(new java.awt.Color(0, 0, 0));
        username1.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        username1.setText("Username");
        getContentPane().add(username1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));

        loginbtn1.setBackground(new java.awt.Color(255, 255, 0));
        loginbtn1.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        loginbtn1.setText("SIGN IN");
        loginbtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbtn1ActionPerformed(evt);
            }
        });
        getContentPane().add(loginbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, -1, -1));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\METHNI\\Downloads\\peakpx (5).jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbtnActionPerformed
        loginpageman log  = new loginpageman();
        log.setVisible(true);
        this.setVisible(false);


    }//GEN-LAST:event_loginbtnActionPerformed

    private void cancelbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelbtnActionPerformed
        firstpage first  = new firstpage();
        first.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_cancelbtnActionPerformed

    private void loginbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbtn1ActionPerformed
        String username =  usernamef.getText();
        String password =  passwordf.getText();
        
        try{
            String sqlquery = "SELECT * FROM signup WHERE username = '"+username+"' AND password = '"+password+"'";
            p = c.prepareStatement(sqlquery);
            r = p.executeQuery();
           
            if (!r.next()) {  
            JOptionPane.showMessageDialog(rootPane, "Error sign in", "Warning",0); 
            usernamef.setText(null);  
            passwordf.setText(null); 

        }

        else {
            JOptionPane.showMessageDialog(rootPane, "Sign in Successful", "Message",0);  
            cashierpage menu = new cashierpage();
            menu.setVisible(true);
            this.setVisible(false);

        }
    } catch(Exception e) {
                JOptionPane.showMessageDialog( null, e);  
                }
    }//GEN-LAST:event_loginbtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginpagecashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginpagecashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginpagecashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginpagecashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginpagecashier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel login;
    private javax.swing.JButton loginbtn;
    private javax.swing.JButton loginbtn1;
    private javax.swing.JLabel password;
    private javax.swing.JPasswordField passwordf;
    private javax.swing.JLabel username;
    private javax.swing.JLabel username1;
    private javax.swing.JTextField usernamef;
    // End of variables declaration//GEN-END:variables
}
