/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.oopassignment3;


public class managerpage extends javax.swing.JFrame {

    /**
     * Creates new form managerpage
     */
    public managerpage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        createaccbtn = new javax.swing.JButton();
        addbtn = new javax.swing.JButton();
        searchbtn = new javax.swing.JButton();
        viewbtn1 = new javax.swing.JButton();
        menu = new javax.swing.JLabel();
        cancelbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        createaccbtn.setBackground(new java.awt.Color(255, 255, 0));
        createaccbtn.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        createaccbtn.setText("REGISTER");
        createaccbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createaccbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createaccbtnActionPerformed(evt);
            }
        });
        jPanel1.add(createaccbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, -1, -1));

        addbtn.setBackground(new java.awt.Color(255, 255, 0));
        addbtn.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        addbtn.setText("ADD ITEMS");
        addbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });
        jPanel1.add(addbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, -1, -1));

        searchbtn.setBackground(new java.awt.Color(255, 255, 0));
        searchbtn.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        searchbtn.setText("SEARCH ITEMS");
        searchbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });
        jPanel1.add(searchbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, -1, -1));

        viewbtn1.setBackground(new java.awt.Color(255, 255, 0));
        viewbtn1.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        viewbtn1.setText("VIEW ITEMS");
        viewbtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewbtn1ActionPerformed(evt);
            }
        });
        jPanel1.add(viewbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, -1, -1));

        menu.setFont(new java.awt.Font("Nirmala UI", 1, 30)); // NOI18N
        menu.setText("Menu");
        jPanel1.add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, -1, -1));

        cancelbtn.setBackground(new java.awt.Color(255, 255, 0));
        cancelbtn.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        cancelbtn.setText("CANCEL");
        cancelbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelbtnActionPerformed(evt);
            }
        });
        jPanel1.add(cancelbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 500, -1, -1));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\METHNI\\Downloads\\peakpx (5).jpg")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createaccbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createaccbtnActionPerformed
        signuppage reg = new signuppage();
        reg.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_createaccbtnActionPerformed

    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed
        addproductpage addp  = new addproductpage();
        addp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_addbtnActionPerformed

    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed

        searchpage1 search = new searchpage1();
        search.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_searchbtnActionPerformed

    private void viewbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewbtn1ActionPerformed
        viewpage_1 view  = new viewpage_1();
        view.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_viewbtn1ActionPerformed

    private void cancelbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelbtnActionPerformed
        loginpageman log  = new loginpageman();
        log.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_cancelbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(managerpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(managerpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(managerpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(managerpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new managerpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbtn;
    private javax.swing.JButton cancelbtn;
    private javax.swing.JButton createaccbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel menu;
    private javax.swing.JButton searchbtn;
    private javax.swing.JButton viewbtn1;
    // End of variables declaration//GEN-END:variables
}
