/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.oopassignment3;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

public class searchpage extends javax.swing.JFrame {

  Connection c = null;
  PreparedStatement p = null;
  ResultSet r = null;
  
    public searchpage() {
        initComponents();
        c = Oopassignment3.c(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        productno = new javax.swing.JLabel();
        productnof = new javax.swing.JTextField();
        productname = new javax.swing.JLabel();
        productnamef = new javax.swing.JTextField();
        stockcount = new javax.swing.JLabel();
        stockcountf = new javax.swing.JTextField();
        price = new javax.swing.JLabel();
        pricef = new javax.swing.JTextField();
        searchbtn = new javax.swing.JButton();
        cancelbtn = new javax.swing.JButton();
        login = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        productno.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        productno.setText("Product No");
        getContentPane().add(productno, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, -1));

        productnof.setBackground(new java.awt.Color(255, 255, 51));
        productnof.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        productnof.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productnofActionPerformed(evt);
            }
        });
        getContentPane().add(productnof, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 160, -1));

        productname.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        productname.setText("Product Name");
        getContentPane().add(productname, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, -1, -1));

        productnamef.setBackground(new java.awt.Color(255, 255, 51));
        productnamef.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        productnamef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productnamefActionPerformed(evt);
            }
        });
        getContentPane().add(productnamef, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 160, -1));

        stockcount.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        stockcount.setText("Stock count");
        getContentPane().add(stockcount, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, -1, -1));

        stockcountf.setBackground(new java.awt.Color(255, 255, 51));
        stockcountf.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        getContentPane().add(stockcountf, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 160, -1));

        price.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        price.setText("Price");
        getContentPane().add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, -1, 29));

        pricef.setBackground(new java.awt.Color(255, 255, 51));
        pricef.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        getContentPane().add(pricef, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 160, -1));

        searchbtn.setBackground(new java.awt.Color(255, 255, 0));
        searchbtn.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        searchbtn.setText("SEARCH");
        searchbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });
        getContentPane().add(searchbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, -1, -1));

        cancelbtn.setBackground(new java.awt.Color(255, 255, 0));
        cancelbtn.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        cancelbtn.setText("CANCEL");
        cancelbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelbtnActionPerformed(evt);
            }
        });
        getContentPane().add(cancelbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 390, -1, -1));

        login.setFont(new java.awt.Font("Nirmala UI", 1, 30)); // NOI18N
        login.setText("Search");
        getContentPane().add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, -1, -1));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\METHNI\\Downloads\\peakpx (5).jpg")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void productnofActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productnofActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productnofActionPerformed

    private void productnamefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productnamefActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productnamefActionPerformed

    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed
        try{
            p = c.prepareStatement("select productno,productname,stockcount,price from addproducts where productno=?");
            int productno = Integer.parseInt(productnof.getText());
            p.setInt(1,productno);
            ResultSet r = p.executeQuery();
            if(r.next()==false) {
                JOptionPane.showMessageDialog(this,"Record not found");
            }
            else{

                productnof.setText(r.getString("productno"));
                productnamef.setText(r.getString("productname"));
                stockcountf.setText(r.getString("stockcount"));
                pricef.setText(r.getString("price"));
            }

        }catch (Exception e) {
            JOptionPane.showMessageDialog( null, e);

        }
    }//GEN-LAST:event_searchbtnActionPerformed

    private void cancelbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelbtnActionPerformed
        cashierpage menu  = new cashierpage();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_cancelbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(searchpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(searchpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(searchpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(searchpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new searchpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelbtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel login;
    private javax.swing.JLabel price;
    private javax.swing.JTextField pricef;
    private javax.swing.JLabel productname;
    private javax.swing.JTextField productnamef;
    private javax.swing.JLabel productno;
    private javax.swing.JTextField productnof;
    private javax.swing.JButton searchbtn;
    private javax.swing.JLabel stockcount;
    private javax.swing.JTextField stockcountf;
    // End of variables declaration//GEN-END:variables
}
