/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.oopassignment3;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;


public class signuppage extends javax.swing.JFrame {

  Connection c = null;
  PreparedStatement p = null;
  ResultSet r = null;
  
    public signuppage() {
        initComponents();
         c = Oopassignment3.c();               
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        login = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        idf = new javax.swing.JTextField();
        usernamef1 = new javax.swing.JTextField();
        username2 = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        passwordf = new javax.swing.JPasswordField();
        loginbtn1 = new javax.swing.JButton();
        cancelbtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        login.setFont(new java.awt.Font("Nirmala UI", 1, 30)); // NOI18N
        login.setText("Sign up");
        getContentPane().add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, -1, -1));

        id.setBackground(new java.awt.Color(0, 0, 0));
        id.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        id.setText("ID");
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        idf.setBackground(new java.awt.Color(255, 255, 51));
        idf.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        getContentPane().add(idf, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 160, -1));

        usernamef1.setBackground(new java.awt.Color(255, 255, 51));
        usernamef1.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        getContentPane().add(usernamef1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 160, -1));

        username2.setBackground(new java.awt.Color(0, 0, 0));
        username2.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        username2.setText("Username");
        getContentPane().add(username2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, -1));

        password.setBackground(new java.awt.Color(0, 0, 0));
        password.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        password.setText("Password");
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, -1, -1));

        passwordf.setBackground(new java.awt.Color(255, 255, 51));
        passwordf.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        getContentPane().add(passwordf, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 160, -1));

        loginbtn1.setBackground(new java.awt.Color(255, 255, 0));
        loginbtn1.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        loginbtn1.setText("SIGN UP");
        loginbtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbtn1ActionPerformed(evt);
            }
        });
        getContentPane().add(loginbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, -1, -1));

        cancelbtn.setBackground(new java.awt.Color(255, 255, 0));
        cancelbtn.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        cancelbtn.setText("CANCEL");
        cancelbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelbtnActionPerformed(evt);
            }
        });
        getContentPane().add(cancelbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, -1, -1));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\METHNI\\Downloads\\peakpx (5).jpg")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\METHNI\\Downloads\\peakpx (5).jpg")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelbtnActionPerformed
            managerpage menu = new managerpage();
            menu.setVisible(true);
            this.setVisible(false); 
    }//GEN-LAST:event_cancelbtnActionPerformed

    private void loginbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbtn1ActionPerformed
        String id = idf.getText();
        String username = usernamef1.getText();
        String password = passwordf.getText();

        
        String sqlquery = "INSERT INTO signup (id,username,password) VALUES ('"+id+"','"+username+"','"+password+"')";
        try{
            p = c.prepareStatement(sqlquery);
            if(id.isEmpty() && username.isEmpty() &&password.isEmpty() ) {
            JOptionPane.showMessageDialog(this, "All fields are mandatory");               
            }
            else{
            JOptionPane.showMessageDialog(this, "Successfully signned up to the system");
            
            managerpage menu = new managerpage();
            menu.setVisible(true);
            this.setVisible(false); 
            }
            p.execute();
            
        }catch (Exception e) {
            JOptionPane.showMessageDialog( null, e);  
    }
    }//GEN-LAST:event_loginbtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signuppage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signuppage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signuppage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signuppage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signuppage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelbtn;
    private javax.swing.JLabel id;
    private javax.swing.JTextField idf;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel login;
    private javax.swing.JButton loginbtn1;
    private javax.swing.JLabel password;
    private javax.swing.JPasswordField passwordf;
    private javax.swing.JLabel username2;
    private javax.swing.JTextField usernamef1;
    // End of variables declaration//GEN-END:variables
}
