/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.oopassignment3;


public class viewpage extends javax.swing.JFrame {

    /**
     * Creates new form viewpage
     */
    public viewpage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        mac2 = new javax.swing.JLabel();
        text5 = new javax.swing.JLabel();
        mac5 = new javax.swing.JLabel();
        text10 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        text9 = new javax.swing.JLabel();
        iphone2 = new javax.swing.JLabel();
        iphone3 = new javax.swing.JLabel();
        text11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        watch2 = new javax.swing.JLabel();
        text2 = new javax.swing.JLabel();
        watch3 = new javax.swing.JLabel();
        text4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        airpods3 = new javax.swing.JLabel();
        username4 = new javax.swing.JLabel();
        airpods2 = new javax.swing.JLabel();
        username2 = new javax.swing.JLabel();
        cancelbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menu.setFont(new java.awt.Font("Nirmala UI", 1, 30)); // NOI18N
        menu.setText("Items");
        getContentPane().add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, -1, -1));

        jPanel9.setBackground(new java.awt.Color(0, 0, 0,80));

        mac2.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        mac2.setForeground(new java.awt.Color(255, 255, 255));
        mac2.setIcon(new javax.swing.ImageIcon("C:\\Users\\METHNI\\Desktop\\OOP ASSIGNMENT 1\\air13.png")); // NOI18N

        text5.setFont(new java.awt.Font("Nirmala UI", 1, 15)); // NOI18N
        text5.setForeground(new java.awt.Color(255, 255, 255));
        text5.setText("MacBook Air 13”");

        mac5.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        mac5.setForeground(new java.awt.Color(255, 255, 255));
        mac5.setIcon(new javax.swing.ImageIcon("C:\\Users\\METHNI\\Desktop\\OOP ASSIGNMENT 1\\pro14.png")); // NOI18N

        text10.setFont(new java.awt.Font("Nirmala UI", 1, 15)); // NOI18N
        text10.setForeground(new java.awt.Color(255, 255, 255));
        text10.setText("MacBook Pro 14” ");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(mac2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(text5))
                .addGap(33, 33, 33))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(text10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(mac5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mac2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(text5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mac5)
                .addGap(18, 18, 18)
                .addComponent(text10)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 130, 180, 300));

        jPanel8.setBackground(new java.awt.Color(0, 0, 0,80));

        text9.setFont(new java.awt.Font("Nirmala UI", 1, 15)); // NOI18N
        text9.setForeground(new java.awt.Color(255, 255, 255));
        text9.setText("iPhone 14");

        iphone2.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        iphone2.setForeground(new java.awt.Color(255, 255, 255));
        iphone2.setIcon(new javax.swing.ImageIcon("C:\\Users\\METHNI\\Desktop\\OOP ASSIGNMENT 1\\14_1.png")); // NOI18N

        iphone3.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        iphone3.setForeground(new java.awt.Color(255, 255, 255));
        iphone3.setIcon(new javax.swing.ImageIcon("C:\\Users\\METHNI\\Desktop\\OOP ASSIGNMENT 1\\14_pro.png")); // NOI18N

        text11.setFont(new java.awt.Font("Nirmala UI", 1, 15)); // NOI18N
        text11.setForeground(new java.awt.Color(255, 255, 255));
        text11.setText("iPhone 14 Pro");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 45, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(text11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(text9))
                            .addComponent(iphone2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(iphone3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(iphone2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(text9)
                .addGap(18, 18, 18)
                .addComponent(iphone3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(text11)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 170, 300));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0,80));

        watch2.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        watch2.setForeground(new java.awt.Color(255, 255, 255));
        watch2.setIcon(new javax.swing.ImageIcon("C:\\Users\\METHNI\\Desktop\\OOP ASSIGNMENT 1\\ultra.png")); // NOI18N

        text2.setFont(new java.awt.Font("Nirmala UI", 1, 15)); // NOI18N
        text2.setForeground(new java.awt.Color(255, 255, 255));
        text2.setText("Apple Watch  Ultra");

        watch3.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        watch3.setForeground(new java.awt.Color(255, 255, 255));
        watch3.setIcon(new javax.swing.ImageIcon("C:\\Users\\METHNI\\Desktop\\OOP ASSIGNMENT 1\\se.png")); // NOI18N

        text4.setFont(new java.awt.Font("Nirmala UI", 1, 15)); // NOI18N
        text4.setForeground(new java.awt.Color(255, 255, 255));
        text4.setText("Apple Watch  SE");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(watch2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(text4)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(watch3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(15, 15, 15))
                                .addComponent(text2)))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(watch2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(text2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(watch3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(text4)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 180, 300));

        jPanel7.setBackground(new java.awt.Color(0, 0, 0,80));

        airpods3.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        airpods3.setForeground(new java.awt.Color(255, 255, 255));
        airpods3.setIcon(new javax.swing.ImageIcon("C:\\Users\\METHNI\\Desktop\\OOP ASSIGNMENT 1\\airpods-max.png")); // NOI18N

        username4.setFont(new java.awt.Font("Nirmala UI", 1, 15)); // NOI18N
        username4.setForeground(new java.awt.Color(255, 255, 255));
        username4.setText("AirPod Max");

        airpods2.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        airpods2.setForeground(new java.awt.Color(255, 255, 255));
        airpods2.setIcon(new javax.swing.ImageIcon("C:\\Users\\METHNI\\Desktop\\OOP ASSIGNMENT 1\\airpods.png")); // NOI18N

        username2.setFont(new java.awt.Font("Nirmala UI", 1, 15)); // NOI18N
        username2.setForeground(new java.awt.Color(255, 255, 255));
        username2.setText("AirPods 3rd Generation");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(airpods3)
                .addGap(32, 32, 32))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(username4))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(username2)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(airpods2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(airpods3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(username4)
                .addGap(18, 18, 18)
                .addComponent(airpods2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(username2)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 180, 300));

        cancelbtn.setBackground(new java.awt.Color(255, 255, 0));
        cancelbtn.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        cancelbtn.setText("CANCEL");
        cancelbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelbtnActionPerformed(evt);
            }
        });
        getContentPane().add(cancelbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 510, -1, -1));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\METHNI\\Downloads\\peakpx (5).jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelbtnActionPerformed
        cashierpage c  = new cashierpage();
        c.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_cancelbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel airpods2;
    private javax.swing.JLabel airpods3;
    private javax.swing.JButton cancelbtn;
    private javax.swing.JLabel iphone2;
    private javax.swing.JLabel iphone3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel mac2;
    private javax.swing.JLabel mac5;
    private javax.swing.JLabel menu;
    private javax.swing.JLabel text10;
    private javax.swing.JLabel text11;
    private javax.swing.JLabel text2;
    private javax.swing.JLabel text4;
    private javax.swing.JLabel text5;
    private javax.swing.JLabel text9;
    private javax.swing.JLabel username2;
    private javax.swing.JLabel username4;
    private javax.swing.JLabel watch2;
    private javax.swing.JLabel watch3;
    // End of variables declaration//GEN-END:variables
}
